using UnityEngine;

public class ItemList : MonoBehaviour
{
    [SerializeField] Item item_1;
    [SerializeField] Item item_2;
    [SerializeField] Item item_3;
    [SerializeField] Item item_4;
    [SerializeField] Item item_5;
    [SerializeField] Item item_6;
    [SerializeField] Item item_7;
    [SerializeField] Item item_8;
    [SerializeField] Item item_9;
    [SerializeField] Item item_10;
    [SerializeField] Item item_11;
    [SerializeField] Item item_12;
    [SerializeField] Item item_13;
    [SerializeField] Item item_14;
    [SerializeField] Item item_15;
    [SerializeField] Item item_16;
    [SerializeField] Item item_17;
    [SerializeField] Item item_18;
    [SerializeField] Item item_19;
    [SerializeField] Item item_20;
    [SerializeField] Item item_21;
    [SerializeField] Item item_22;
    [SerializeField] Item item_23;
    [SerializeField] Item item_24;
    [SerializeField] Item item_25;
    [SerializeField] Item item_26;
    [SerializeField] Item item_27;
    [SerializeField] Item item_28;
    [SerializeField] Item item_29;
    [SerializeField] Item item_30;
    [SerializeField] Item item_31;
    [SerializeField] Item item_32;
    [SerializeField] Item item_33;
    [SerializeField] Item item_34;
    [SerializeField] Item item_35;
    [SerializeField] Item item_36;
    [SerializeField] Item item_37;
    [SerializeField] Item item_38;
    [SerializeField] Item item_39;
    [SerializeField] Item item_40;
    [SerializeField] Item item_41;
    [SerializeField] Item item_42;
    [SerializeField] Item item_43;
    [SerializeField] Item item_44;
    [SerializeField] Item item_45;
    [SerializeField] Item item_46;
    [SerializeField] Item item_47;
    [SerializeField] Item item_48;
    [SerializeField] Item item_49;
    [SerializeField] Item item_50;
    [SerializeField] Item item_51;
    [SerializeField] Item item_52;
    [SerializeField] Item item_53;
    [SerializeField] Item item_54;
    [SerializeField] Item item_55;
    [SerializeField] Item item_56;
    [SerializeField] Item item_57;
    [SerializeField] Item item_58;
    [SerializeField] Item item_59;
    [SerializeField] Item item_60;
    [SerializeField] Item item_61;
    [SerializeField] Item item_62;
    [SerializeField] Item item_63;
    [SerializeField] Item item_64;
    [SerializeField] Item item_65;
    [SerializeField] Item item_66;
    [SerializeField] Item item_67;
    [SerializeField] Item item_68;
    [SerializeField] Item item_69;
    [SerializeField] Item item_70;
    [SerializeField] Item item_71;
    [SerializeField] Item item_72;
    [SerializeField] Item item_73;
    [SerializeField] Item item_74;
    [SerializeField] Item item_75;

    public Item GetItem(int i)
    {
        if (i == 1) return item_1;
        else if (i == 2) return item_2;
        else if (i == 3) return item_3;
        else if (i == 4) return item_4;
        else if (i == 5) return item_5;
        else if (i == 6) return item_6;
        else if (i == 7) return item_7;
        else if (i == 8) return item_8;
        else if (i == 9) return item_9;
        else if (i == 10) return item_10;
        else if (i == 11) return item_11;
        else if (i == 12) return item_12;
        else if (i == 13) return item_13;
        else if (i == 14) return item_14;
        else if (i == 15) return item_15;
        else if (i == 16) return item_16;
        else if (i == 17) return item_17;
        else if (i == 18) return item_18;
        else if (i == 19) return item_19;
        else if (i == 20) return item_20;
        else if (i == 21) return item_21;
        else if (i == 22) return item_22;
        else if (i == 23) return item_23;
        else if (i == 24) return item_24;
        else if (i == 25) return item_25;
        else if (i == 26) return item_26;
        else if (i == 27) return item_27;
        else if (i == 28) return item_28;
        else if (i == 29) return item_29;
        else if (i == 30) return item_30;
        else if (i == 31) return item_31;
        else if (i == 32) return item_32;
        else if (i == 33) return item_33;
        else if (i == 34) return item_34;
        else if (i == 35) return item_35;
        else if (i == 36) return item_36;
        else if (i == 37) return item_37;
        else if (i == 38) return item_38;
        else if (i == 39) return item_39;
        else if (i == 40) return item_40;
        else if (i == 41) return item_41;
        else if (i == 42) return item_42;
        else if (i == 43) return item_43;
        else if (i == 44) return item_44;
        else if (i == 45) return item_45;
        else if (i == 46) return item_46;
        else if (i == 47) return item_47;
        else if (i == 48) return item_48;
        else if (i == 49) return item_49;
        else if (i == 50) return item_50;
        else if (i == 51) return item_51;
        else if (i == 52) return item_52;
        else if (i == 53) return item_53;
        else if (i == 54) return item_54;
        else if (i == 55) return item_55;
        else if (i == 56) return item_56;
        else if (i == 57) return item_57;
        else if (i == 58) return item_58;
        else if (i == 59) return item_59;
        else if (i == 60) return item_60;
        else if (i == 61) return item_61;
        else if (i == 62) return item_62;
        else if (i == 63) return item_63;
        else if (i == 64) return item_64;
        else if (i == 65) return item_65;
        else if (i == 66) return item_66;
        else if (i == 67) return item_67;
        else if (i == 68) return item_68;
        else if (i == 69) return item_69;
        else if (i == 70) return item_70;
        else if (i == 71) return item_71;
        else if (i == 72) return item_72;
        else if (i == 73) return item_73;
        else if (i == 74) return item_74;
        else if (i == 75) return item_75;
        return item_1;
    }
}
